@startuml server

class Caress {    
    .. public ..
        Caress(uint8_t pins[], int size)
        void run(unsigned long time)
        void start(unsigned long startingTime, int interval, int shift)
        void shake(unsigned long time)
        void notify(uint8_t repeat)
    .. private ..
        uint8_t _pins[MAX_PINS]
        int _step
        int _interval
        int _shift
        int _numOfVib
        int _numOfSteps
        bool _caressing
        bool _shaking
        unsigned long _lastCaress   
        unsigned long _lastShake    
}

class Hug {    
    .. public ..
        Hug(unsigned long inflateCooldown, unsigned long startCooldown)
        void run(unsigned long time)
        void start(unsigned long startingTime)
    .. private ..
        uint8_t _light
        bool _hugging
        unsigned long _lastHug
        unsigned long _inflateCooldown
        unsigned long _startCooldown   
}

class Heat {    
    .. public ..
        Heat(float dutyCycle)
        void run(unsigned long time)
        void start(unsigned long startingTime)
    .. private ..
        bool _heating
        unsigned long _lastHeat
        unsigned long _heatingTime
        unsigned long _cooldown
}

class WiFiConnection {
    .. public ..
        WiFiConnection(WiFiServer server)
        int getPort()
        bool searchClient()
        void setup()
        bool isClientConnected()
        bool checkMessage()
        char readMessage()
        void stopClient()
    .. private ..
        void printData()
        int _port
        IPAddress _ip = *(new IPAddress(192, 168, 43, 179))
        IPAddress _gateway = *(new IPAddress(192, 168, 43, 1))
        IPAddress _subnet = *(new IPAddress(255, 255, 255, 0))
        WiFiServer _server = 0
        WiFiClient _client
        Credentials _credentials
}

class Credantials {
    .. public ..
        Credentials()
        void search()
        bool arePresent()
        bool readFromMemory()
        String getSsid()
        String getPassword()
    .. private ..
        bool _arePresent = false
        String _password, _ssid
        const String SSID_prefix = "SSID: "
        const String PSW_prefix = "Password: "
}

Credantials -u-> "use" WiFiConnection 

@enduml